#!/bin/bash

# Daily TIL Generator - Creates a PR with a new TIL article from shell history
# This script is meant to be run as a daily cron job

set -euo pipefail

# Load environment variables from .env file if it exists
if [ -f "$HOME/.env" ]; then
    set -a
    source "$HOME/.env"
    set +a
fi

# Configuration
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
BLOG_REPO_PATH="${BLOG_REPO_PATH:-$HOME/src/github.com/leblancfg/leblancfg.github.io}"
PYTHON_SCRIPT="$SCRIPT_DIR/generate_til.py"
LOG_FILE="$HOME/.til_generator.log"

# Function to log messages
log_message() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOG_FILE"
}

# Function to cleanup on exit
cleanup() {
    if [ $? -ne 0 ]; then
        log_message "Script failed, cleaning up..."
        cd "$BLOG_REPO_PATH" 2>/dev/null && git checkout dev 2>/dev/null || true
    fi
}
trap cleanup EXIT

# Check requirements
if [ ! -f "$PYTHON_SCRIPT" ]; then
    log_message "Error: Python script not found at $PYTHON_SCRIPT"
    exit 1
fi

if [ ! -d "$BLOG_REPO_PATH" ]; then
    log_message "Error: Blog repository not found at $BLOG_REPO_PATH"
    log_message "Set BLOG_REPO_PATH environment variable to your blog repo location"
    exit 1
fi

# Check for required environment variables
if [ -z "${OPENAI_API_KEY:-}" ]; then
    log_message "Error: OPENAI_API_KEY environment variable not set"
    exit 1
fi

# Navigate to blog repository
cd "$BLOG_REPO_PATH"

# Ensure we're on the dev branch and up to date (dev is the base for feature branches)
log_message "Updating blog repository..."
git checkout dev > /dev/null 2>&1
git pull origin dev > /dev/null 2>&1

# Generate the TIL article using UV
log_message "Generating TIL article..."
GENERATION_OUTPUT=$(cd "$SCRIPT_DIR" && uv run python generate_til.py 2>&1) || {
    log_message "Failed to generate TIL article"
    log_message "$GENERATION_OUTPUT"
    exit 1
}

# Extract the post file path from output
POST_FILE=$(echo "$GENERATION_OUTPUT" | grep "^POST_FILE=" | cut -d'=' -f2)

if [ -z "$POST_FILE" ] || [ ! -f "$POST_FILE" ]; then
    log_message "No TIL article was generated (nothing interesting found today)"
    exit 0
fi

# Get the article title from the file
TITLE=$(grep "^title:" "$POST_FILE" | sed 's/^title: "\(.*\)"$/\1/')

# Create a new branch
BRANCH_NAME="til-$(date +%Y%m%d)-$(echo "$TITLE" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/--*/-/g' | sed 's/^-//;s/-$//' | cut -c1-50)"
log_message "Creating branch: $BRANCH_NAME"

git checkout -b "$BRANCH_NAME" > /dev/null 2>&1

# Add and commit the new file
git add "$POST_FILE"
git commit -m "Add TIL: $TITLE

Automatically generated from shell history analysis.
Generated on $(date '+%Y-%m-%d')" > /dev/null 2>&1

# Push the branch
log_message "Pushing branch to remote..."
git push -u origin "$BRANCH_NAME" > /dev/null 2>&1

# Create PR using GitHub CLI (if available)
if command -v gh &> /dev/null; then
    log_message "Creating pull request..."
    PR_BODY="## Today I Learned: $TITLE

This TIL article was automatically generated from my shell history using AI analysis.

**Date**: $(date '+%Y-%m-%d')
**File**: \`$(basename "$POST_FILE")\`

### Review Checklist
- [ ] Content is accurate and helpful
- [ ] No sensitive information included
- [ ] Formatting looks good
- [ ] Tags are appropriate

---
*Generated by the daily TIL generator script*"

    PR_URL=$(gh pr create \
        --title "TIL: $TITLE" \
        --body "$PR_BODY" \
        --base dev \
        --head "$BRANCH_NAME" \
        2>&1) || {
        log_message "Failed to create PR. You can create it manually."
        log_message "Branch $BRANCH_NAME has been pushed to remote."
    }
    
    if [ -n "${PR_URL:-}" ]; then
        log_message "Pull request created: $PR_URL"
    fi
else
    log_message "GitHub CLI not found. Please install 'gh' for automatic PR creation."
    log_message "Branch $BRANCH_NAME has been pushed. Create a PR manually."
fi

# Return to dev branch
git checkout dev > /dev/null 2>&1

log_message "TIL generation complete!"